# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(913, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 891, 441))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_upload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_upload.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.btn_upload.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_upload.setObjectName("btn_upload")
        self.btn_download = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_download.setGeometry(QtCore.QRect(160, 10, 131, 31))
        self.btn_download.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_download.setObjectName("btn_download")
        self.btn_run_all = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_run_all.setGeometry(QtCore.QRect(10, 500, 131, 51))
        self.btn_run_all.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_run_all.setObjectName("btn_run_all")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(170, 530, 731, 23))
        self.progressBar.setProperty("value", 1)
        self.progressBar.setObjectName("progressBar")
        self.label_on_progress_bar = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_on_progress_bar.setGeometry(QtCore.QRect(170, 510, 691, 16))
        self.label_on_progress_bar.setObjectName("label_on_progress_bar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 913, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_upload.setText(_translate("MainWindow", "Upload Excel/CSV"))
        self.btn_download.setText(_translate("MainWindow", "Download Template"))
        self.btn_run_all.setText(_translate("MainWindow", "Run All"))
        self.label_on_progress_bar.setText(_translate("MainWindow", "Checking..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
